apiVersion: v1
kind: Service
metadata:
  name: globalmedicare-backend-service
spec:
  selector:
    app: globalmedicare-backend
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
