pipeline {
    agent any

    stages {
        stage('Delete KIND Cluster') {
            steps {
                echo 'Checking for existing KIND cluster...'
                sh '''
                    if kind get clusters | grep -q "kind"; then
                        echo "KIND cluster found. Deleting..."
                            kind delete cluster
                            echo "KIND cluster deleted successfully."
                    else
                        echo "No KIND cluster found. Skipping delete."
                    fi
                '''
            }
        }
    }
}
